# flake8: noqa

"""
    xpan

    xpanapi  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

from .api_client import *
from .configuration import Configuration
